services:
  ogd-backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    container_name: ogd-backend
    depends_on:
      - mongodb
    restart: always #restart on boot
  ogd-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev #change on prod
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - 3001:3001
    env_file:
      - ./frontend/.env
    container_name: ogd-frontend
    depends_on:
      - ogd-backend
    restart: always #restart on boot
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    command: ["--auth"]
    restart: always #restart on boot

volumes:
  mongo_data: